/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AuthenticatedAcademicYearsIndexRouteImport } from './routes/_authenticated/academic-years/index'
import { Route as AuthenticatedTeachersNewRouteImport } from './routes/_authenticated/teachers/new'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students/new'
import { Route as AuthenticatedSchoolsNewRouteImport } from './routes/_authenticated/schools/new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicYearsIndexRoute =
  AuthenticatedAcademicYearsIndexRouteImport.update({
    id: '/academic-years/',
    path: '/academic-years/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersNewRoute =
  AuthenticatedTeachersNewRouteImport.update({
    id: '/teachers/new',
    path: '/teachers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsNewRoute = AuthenticatedSchoolsNewRouteImport.update({
  id: '/schools/new',
  path: '/schools/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schools/new': typeof AuthenticatedSchoolsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/academic-years/': typeof AuthenticatedAcademicYearsIndexRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schools/new': typeof AuthenticatedSchoolsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/academic-years': typeof AuthenticatedAcademicYearsIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/schools/new': typeof AuthenticatedSchoolsNewRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/_authenticated/academic-years/': typeof AuthenticatedAcademicYearsIndexRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/schools/new'
    | '/students/new'
    | '/teachers/new'
    | '/academic-years/'
    | '/classes/'
    | '/schools/'
    | '/students/'
    | '/subjects/'
    | '/teachers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/schools/new'
    | '/students/new'
    | '/teachers/new'
    | '/academic-years'
    | '/classes'
    | '/schools'
    | '/students'
    | '/subjects'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/schools/new'
    | '/_authenticated/students/new'
    | '/_authenticated/teachers/new'
    | '/_authenticated/academic-years/'
    | '/_authenticated/classes/'
    | '/_authenticated/schools/'
    | '/_authenticated/students/'
    | '/_authenticated/subjects/'
    | '/_authenticated/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years/': {
      id: '/_authenticated/academic-years/'
      path: '/academic-years'
      fullPath: '/academic-years/'
      preLoaderRoute: typeof AuthenticatedAcademicYearsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/new': {
      id: '/_authenticated/teachers/new'
      path: '/teachers/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof AuthenticatedTeachersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/new': {
      id: '/_authenticated/schools/new'
      path: '/schools/new'
      fullPath: '/schools/new'
      preLoaderRoute: typeof AuthenticatedSchoolsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSchoolsNewRoute: typeof AuthenticatedSchoolsNewRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedTeachersNewRoute: typeof AuthenticatedTeachersNewRoute
  AuthenticatedAcademicYearsIndexRoute: typeof AuthenticatedAcademicYearsIndexRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSchoolsNewRoute: AuthenticatedSchoolsNewRoute,
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedTeachersNewRoute: AuthenticatedTeachersNewRoute,
  AuthenticatedAcademicYearsIndexRoute: AuthenticatedAcademicYearsIndexRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
