/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTimetableIndexRouteImport } from './routes/_authenticated/timetable/index'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedParentsIndexRouteImport } from './routes/_authenticated/parents/index'
import { Route as AuthenticatedFeesIndexRouteImport } from './routes/_authenticated/fees/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAcademicYearsIndexRouteImport } from './routes/_authenticated/academic-years/index'
import { Route as AuthenticatedTeachersNewRouteImport } from './routes/_authenticated/teachers/new'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students/new'
import { Route as AuthenticatedSchoolsNewRouteImport } from './routes/_authenticated/schools/new'
import { Route as AuthenticatedParentsNewRouteImport } from './routes/_authenticated/parents/new'
import { Route as AuthenticatedFeesNewRouteImport } from './routes/_authenticated/fees/new'
import { Route as AuthenticatedFeesCategoriesRouteImport } from './routes/_authenticated/fees/categories'
import { Route as AuthenticatedFeesIdRouteImport } from './routes/_authenticated/fees/$id'
import { Route as AuthenticatedAttendanceNewRouteImport } from './routes/_authenticated/attendance/new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableIndexRoute =
  AuthenticatedTimetableIndexRouteImport.update({
    id: '/timetable/',
    path: '/timetable/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParentsIndexRoute =
  AuthenticatedParentsIndexRouteImport.update({
    id: '/parents/',
    path: '/parents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesIndexRoute = AuthenticatedFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicYearsIndexRoute =
  AuthenticatedAcademicYearsIndexRouteImport.update({
    id: '/academic-years/',
    path: '/academic-years/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersNewRoute =
  AuthenticatedTeachersNewRouteImport.update({
    id: '/teachers/new',
    path: '/teachers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsNewRoute = AuthenticatedSchoolsNewRouteImport.update({
  id: '/schools/new',
  path: '/schools/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentsNewRoute = AuthenticatedParentsNewRouteImport.update({
  id: '/parents/new',
  path: '/parents/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesNewRoute = AuthenticatedFeesNewRouteImport.update({
  id: '/fees/new',
  path: '/fees/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesCategoriesRoute =
  AuthenticatedFeesCategoriesRouteImport.update({
    id: '/fees/categories',
    path: '/fees/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeesIdRoute = AuthenticatedFeesIdRouteImport.update({
  id: '/fees/$id',
  path: '/fees/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceNewRoute =
  AuthenticatedAttendanceNewRouteImport.update({
    id: '/attendance/new',
    path: '/attendance/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/attendance/new': typeof AuthenticatedAttendanceNewRoute
  '/fees/$id': typeof AuthenticatedFeesIdRoute
  '/fees/categories': typeof AuthenticatedFeesCategoriesRoute
  '/fees/new': typeof AuthenticatedFeesNewRoute
  '/parents/new': typeof AuthenticatedParentsNewRoute
  '/schools/new': typeof AuthenticatedSchoolsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/academic-years/': typeof AuthenticatedAcademicYearsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/fees/': typeof AuthenticatedFeesIndexRoute
  '/parents/': typeof AuthenticatedParentsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/timetable/': typeof AuthenticatedTimetableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/attendance/new': typeof AuthenticatedAttendanceNewRoute
  '/fees/$id': typeof AuthenticatedFeesIdRoute
  '/fees/categories': typeof AuthenticatedFeesCategoriesRoute
  '/fees/new': typeof AuthenticatedFeesNewRoute
  '/parents/new': typeof AuthenticatedParentsNewRoute
  '/schools/new': typeof AuthenticatedSchoolsNewRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/academic-years': typeof AuthenticatedAcademicYearsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/fees': typeof AuthenticatedFeesIndexRoute
  '/parents': typeof AuthenticatedParentsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/timetable': typeof AuthenticatedTimetableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/attendance/new': typeof AuthenticatedAttendanceNewRoute
  '/_authenticated/fees/$id': typeof AuthenticatedFeesIdRoute
  '/_authenticated/fees/categories': typeof AuthenticatedFeesCategoriesRoute
  '/_authenticated/fees/new': typeof AuthenticatedFeesNewRoute
  '/_authenticated/parents/new': typeof AuthenticatedParentsNewRoute
  '/_authenticated/schools/new': typeof AuthenticatedSchoolsNewRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/_authenticated/academic-years/': typeof AuthenticatedAcademicYearsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/fees/': typeof AuthenticatedFeesIndexRoute
  '/_authenticated/parents/': typeof AuthenticatedParentsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/timetable/': typeof AuthenticatedTimetableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/attendance/new'
    | '/fees/$id'
    | '/fees/categories'
    | '/fees/new'
    | '/parents/new'
    | '/schools/new'
    | '/students/new'
    | '/teachers/new'
    | '/academic-years/'
    | '/attendance/'
    | '/classes/'
    | '/fees/'
    | '/parents/'
    | '/reports/'
    | '/schools/'
    | '/students/'
    | '/subjects/'
    | '/teachers/'
    | '/timetable/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/attendance/new'
    | '/fees/$id'
    | '/fees/categories'
    | '/fees/new'
    | '/parents/new'
    | '/schools/new'
    | '/students/new'
    | '/teachers/new'
    | '/academic-years'
    | '/attendance'
    | '/classes'
    | '/fees'
    | '/parents'
    | '/reports'
    | '/schools'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/attendance/new'
    | '/_authenticated/fees/$id'
    | '/_authenticated/fees/categories'
    | '/_authenticated/fees/new'
    | '/_authenticated/parents/new'
    | '/_authenticated/schools/new'
    | '/_authenticated/students/new'
    | '/_authenticated/teachers/new'
    | '/_authenticated/academic-years/'
    | '/_authenticated/attendance/'
    | '/_authenticated/classes/'
    | '/_authenticated/fees/'
    | '/_authenticated/parents/'
    | '/_authenticated/reports/'
    | '/_authenticated/schools/'
    | '/_authenticated/students/'
    | '/_authenticated/subjects/'
    | '/_authenticated/teachers/'
    | '/_authenticated/timetable/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/': {
      id: '/_authenticated/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AuthenticatedTimetableIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parents/': {
      id: '/_authenticated/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof AuthenticatedParentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/': {
      id: '/_authenticated/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof AuthenticatedFeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years/': {
      id: '/_authenticated/academic-years/'
      path: '/academic-years'
      fullPath: '/academic-years/'
      preLoaderRoute: typeof AuthenticatedAcademicYearsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/new': {
      id: '/_authenticated/teachers/new'
      path: '/teachers/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof AuthenticatedTeachersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/new': {
      id: '/_authenticated/schools/new'
      path: '/schools/new'
      fullPath: '/schools/new'
      preLoaderRoute: typeof AuthenticatedSchoolsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parents/new': {
      id: '/_authenticated/parents/new'
      path: '/parents/new'
      fullPath: '/parents/new'
      preLoaderRoute: typeof AuthenticatedParentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/new': {
      id: '/_authenticated/fees/new'
      path: '/fees/new'
      fullPath: '/fees/new'
      preLoaderRoute: typeof AuthenticatedFeesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/categories': {
      id: '/_authenticated/fees/categories'
      path: '/fees/categories'
      fullPath: '/fees/categories'
      preLoaderRoute: typeof AuthenticatedFeesCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees/$id': {
      id: '/_authenticated/fees/$id'
      path: '/fees/$id'
      fullPath: '/fees/$id'
      preLoaderRoute: typeof AuthenticatedFeesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/new': {
      id: '/_authenticated/attendance/new'
      path: '/attendance/new'
      fullPath: '/attendance/new'
      preLoaderRoute: typeof AuthenticatedAttendanceNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAttendanceNewRoute: typeof AuthenticatedAttendanceNewRoute
  AuthenticatedFeesIdRoute: typeof AuthenticatedFeesIdRoute
  AuthenticatedFeesCategoriesRoute: typeof AuthenticatedFeesCategoriesRoute
  AuthenticatedFeesNewRoute: typeof AuthenticatedFeesNewRoute
  AuthenticatedParentsNewRoute: typeof AuthenticatedParentsNewRoute
  AuthenticatedSchoolsNewRoute: typeof AuthenticatedSchoolsNewRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedTeachersNewRoute: typeof AuthenticatedTeachersNewRoute
  AuthenticatedAcademicYearsIndexRoute: typeof AuthenticatedAcademicYearsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedFeesIndexRoute: typeof AuthenticatedFeesIndexRoute
  AuthenticatedParentsIndexRoute: typeof AuthenticatedParentsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedTimetableIndexRoute: typeof AuthenticatedTimetableIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAttendanceNewRoute: AuthenticatedAttendanceNewRoute,
  AuthenticatedFeesIdRoute: AuthenticatedFeesIdRoute,
  AuthenticatedFeesCategoriesRoute: AuthenticatedFeesCategoriesRoute,
  AuthenticatedFeesNewRoute: AuthenticatedFeesNewRoute,
  AuthenticatedParentsNewRoute: AuthenticatedParentsNewRoute,
  AuthenticatedSchoolsNewRoute: AuthenticatedSchoolsNewRoute,
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedTeachersNewRoute: AuthenticatedTeachersNewRoute,
  AuthenticatedAcademicYearsIndexRoute: AuthenticatedAcademicYearsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedFeesIndexRoute: AuthenticatedFeesIndexRoute,
  AuthenticatedParentsIndexRoute: AuthenticatedParentsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedTimetableIndexRoute: AuthenticatedTimetableIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
