REVOKE EXECUTE ON FUNCTION public.get_teacher_id(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_student_id(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_parent_id(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_parent_of_student(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.teacher_teaches_class(uuid, uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.teacher_teaches_student(uuid, uuid) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.get_teacher_id(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_student_id(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_parent_id(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_parent_of_student(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.teacher_teaches_class(uuid, uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.teacher_teaches_student(uuid, uuid) TO authenticated, service_role;